Repository piccolo-orm/piccolo, pull requests merged in 2022-10, with the labels that each got.

#631 version pin Starlite to an older version so it works with FastAPI
  piccolo/apps/asgi/commands/new.py
  piccolo/apps/asgi/commands/templates/app/requirements.txt.jinja
Labels: bug

#642 make sure `Time` column is in `piccolo/columns/__init__.py`
  piccolo/columns/__init__.py
Labels: bug

#644 Improve transaction docs
  docs/src/piccolo/query_types/transactions.rst
Labels: documentation

#645 add docs for `add_raw_backwards`
  docs/src/piccolo/migrations/create.rst
Labels: documentation

#654 fix bug with `MyTable.objects().create()` and non-null values
  piccolo/query/methods/objects.py
  tests/table/instance/test_create.py
Labels: bug

#655 Change `getLogger` arg from `__file__` -> `__name__`
  piccolo/apps/user/tables.py
  piccolo/engine/base.py
Labels: bug

#656 Playground: Option to use ipython profile
  piccolo/apps/playground/commands/run.py
  piccolo/main.py
  pyproject.toml
Labels: enhancement

#661 use Python 3.11 in GitHub actions
  .github/workflows/tests.yaml
Labels: enhancement
