Repository piccolo-orm/piccolo, pull requests merged in 2025-01, with the labels that each got.

#1128 1127 Fix bug with large integers in SQLite
  piccolo/engine/sqlite.py
  requirements/test-requirements.txt
  tests/apps/asgi/commands/files/dummy_server.py
  tests/columns/test_integer.py
Labels: bug

#1138 add Quart asgi template
  README.md
  piccolo/apps/asgi/commands/new.py
  piccolo/apps/asgi/commands/templates/app/_quart_app.py.jinja
  piccolo/apps/asgi/commands/templates/app/app.py.jinja
  piccolo/apps/asgi/commands/templates/app/home/_quart_endpoints.py.jinja
  piccolo/apps/asgi/commands/templates/app/home/endpoints.py.jinja
  piccolo/apps/asgi/commands/templates/app/home/templates/home.html.jinja_raw
Labels: enhancement

#1145 fix constraint typos
  CHANGES.rst
  tests/table/test_insert.py
Labels: documentation

#1147 1113 Use Python 3.13 for integration tests
  .github/workflows/tests.yaml
Labels: testing

#1139 add Falcon asgi template
  README.md
  piccolo/apps/asgi/commands/new.py
  piccolo/apps/asgi/commands/templates/app/_falcon_app.py.jinja
  piccolo/apps/asgi/commands/templates/app/app.py.jinja
  piccolo/apps/asgi/commands/templates/app/home/_falcon_endpoints.py.jinja
  piccolo/apps/asgi/commands/templates/app/home/endpoints.py.jinja
  piccolo/apps/asgi/commands/templates/app/home/templates/home.html.jinja_raw
Labels: enhancement
